"""Tunable conversation defaults."""

from typing import Final

CONVERSATION_PERMISSION_RESPONSE_TIMEOUT_SECONDS: Final = 300
ACP_SESSION_UPDATE_INGRESS_MAX_ITEMS: Final = 1024
ACP_BROWSER_LIVE_QUEUE_MAX_ENVELOPES: Final = 1_024
ACP_CHILD_STDERR_TAIL_MAX_BYTES: Final = 65536
ACP_ACTIVE_PROMPT_CANCEL_TIMEOUT_SECONDS: Final = 10
ACP_CONVERSATION_COMPACTION_CAPTURE_TIMEOUT_SECONDS: Final = 300
ACP_CONVERSATION_SERVICE_SHUTDOWN_TIMEOUT_SECONDS: Final = 10
ACP_NEW_CONVERSATION_TIMEOUT_SECONDS: Final = 30
ACP_REVERSE_TERMINAL_OUTPUT_MAX_BYTES: Final = 1_048_576
ACP_REVERSE_TERMINAL_CLEANUP_TIMEOUT_SECONDS: Final = 5
