"""Build the frozen correction data for the skill-row correction revision.

Each correction names text to replace. A correction is only allowed when the exact
text it replaces occurs verbatim in a version of that skill this repository shipped:
that is the proof the text is the build's and not something the owner wrote. Run this
by hand, read what it prints, and commit the generated module.
"""

from __future__ import annotations

import hashlib
import sqlite3
import subprocess
import sys
from pathlib import Path

REHEARSAL_DB = sys.argv[1]
OUT = Path("src/planner/core/migrations/skill_row_correction_data.py")
PACKAGED = Path("src/planner/skills")


def git(*args: str) -> str:
    return subprocess.run(["git", *args], capture_output=True, text=True).stdout


def shipped_texts(skill: str) -> list[str]:
    path = f"src/planner/skills/{skill}/SKILL.md"
    return [
        git("cat-file", "blob", f"{commit}:{path}")
        for commit in git("log", "--all", "--format=%H", "--", path).split()
    ]


def section(text: str, heading: str) -> str:
    start = text.index(heading)
    end = text.find("\n## ", start + 1)
    return text[start : end if end != -1 else len(text)]


def line(text: str, needle: str) -> str:
    for raw in text.splitlines():
        if needle in raw:
            return raw
    raise LookupError(needle)


conn = sqlite3.connect(REHEARSAL_DB)
rows = {
    name: text for name, text in conn.execute("SELECT skill_name, source_text FROM managed_skills")
}
packaged = {p.parent.name: p.read_text(encoding="utf-8") for p in PACKAGED.glob("*/SKILL.md")}

corrections: list[tuple[str, str, str, str]] = []


def replace_section(skill: str, heading: str, new_text: str, why: str) -> None:
    old = section(rows[skill], heading)
    corrections.append((skill, old + "\n\n" if old + "\n\n" in rows[skill] else old, new_text, why))


def drop_line(skill: str, needle: str, why: str) -> None:
    old = line(rows[skill], needle)
    corrections.append((skill, old + "\n", "", why))


def replace_line(skill: str, needle: str, new_text: str, why: str) -> None:
    corrections.append((skill, line(rows[skill], needle), new_text, why))


# --- panels -------------------------------------------------------------------
replace_section(
    "panels", "## Rollover", "", "the rollover skill is retired and the section with it"
)
replace_line(
    "panels",
    "- `panels chief ...` only for importing",
    line(packaged["panels"], "- `panels send-message --chief ...`"),
    "the chief command group is gone; send-message addresses the Chief now",
)
drop_line("panels", "- **`panels-rollover`** — carrying", "retired skill")
drop_line("panels", "- **`panels-sprint-planning`** — planning", "retired skill")

# --- panels-chief-of-staff ----------------------------------------------------
replace_section(
    "panels-chief-of-staff",
    "## Rollover and sprint planning",
    "",
    "both skills are retired and the section only describes them",
)
drop_line("panels-chief-of-staff", "- **Rollover**: load `panels-rollover`", "retired skill")
drop_line("panels-chief-of-staff", "- **Sprint planning**: use or coordinate", "retired skill")
replace_section(
    "panels-chief-of-staff",
    "## Work completed outside Panels",
    section(packaged["panels-chief-of-staff"], "## Work completed outside Panels").rstrip("\n")
    + "\n\n",
    "the chief command group is gone; external work goes through ordinary Ticket operations",
)

# --- proof --------------------------------------------------------------------
failed = False
for skill, old, _new, why in corrections:
    texts = shipped_texts(skill)
    if not any(old.strip() and old.strip() in text for text in texts):
        print(f"REFUSED  {skill}: replacement text is not in any shipped version — {why}")
        failed = True
    else:
        digest = hashlib.sha256(old.encode()).hexdigest()[:12]
        print(f"proved   {skill:24} {digest}  {len(old):5} chars  {why}")
if failed:
    raise SystemExit("some corrections are not provably build text; nothing written")

body = [
    '"""The exact text the skill-row correction revision replaces, and its proof.',
    "",
    "Each entry replaces text that occurs verbatim in a version of that skill this",
    "repository shipped, so no entry can remove something the owner wrote. Generated by",
    "scripts/build_skill_corrections.py and frozen: a revision records what happened.",
    '"""',
    "",
    "from __future__ import annotations",
    "",
    "from typing import Final",
    "",
    "# (skill name, exact text to replace, replacement, why)",
    "SPAN_CORRECTIONS: Final[tuple[tuple[str, str, str, str], ...]] = (",
]
for skill, old, new, why in corrections:
    body.append("    (")
    body.append(f"        {skill!r},")
    body.append(f"        {old!r},")
    body.append(f"        {new!r},")
    body.append(f"        {why!r},")
    body.append("    ),")
body.append(")")
body.append("")
body.append("# A name that moved. Safe anywhere, including in text the owner wrote, because a")
body.append("# command name is a literal a worker types and not prose.")
body.append("TOKEN_CORRECTIONS: Final[tuple[tuple[str, str], ...]] = (")
body.append('    ("request-user-help", "request-help"),')
body.append(")")
body.append("")
body.append("# What must be absent from these rows once this revision has run. Anything still")
body.append("# here is this revision failing silently, which is the bug it exists to fix.")
body.append("CLAIMS: Final[tuple[tuple[str, str], ...]] = (")
for claim in (
    ("panels", "panels chief"),
    ("panels", "panels-rollover"),
    ("panels", "panels-sprint-planning"),
    ("panels-chief-of-staff", "panels chief"),
    ("panels-chief-of-staff", "panels-rollover"),
    ("panels-chief-of-staff", "panels-sprint-planning"),
    ("panels-chief-of-staff", "needs_success"),
    ("panels-chief-of-staff", "needs_approach"),
    ("panels-chief-of-staff", "needs_closeout"),
    ("panels-worker-planning-midday-check", "request-user-help"),
    ("panels-worker-planning-sprint", "request-user-help"),
):
    body.append(f"    {claim!r},")
body.append(")")
OUT.write_text("\n".join(body) + "\n", encoding="utf-8")
print(f"\nwrote {OUT} with {len(corrections)} corrections")
