"""Declare Worker types and every managed skill in the database.

The structure of a Worker type was a Python module and its editable part was a JSON file
beside the database. Both move here, together with the text of every managed skill, so a
type is declared in one place. The definitions below are a frozen copy of what shipped:
this migration must keep working after those modules are deleted, so it carries its own
copy rather than importing them.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Final

from alembic import op

revision = "worker_types_in_database"
down_revision = "two_ownership_modes"
branch_labels = None
depends_on = None

SKILL_FILE_NAME: Final = "SKILL.md"
RETIRED_SKILL_NAMES: Final = frozenset(
    {
        "panels-rollover",
        "panels-sprint-planning",
        "panels-ticket-management",
        "panels-update-chief-of-staff",
    }
)
# These two skills tell a worker how to declare a Worker type, which is what this change
# replaces. The copy in the skills home describes the way that is going away, so for these
# two the packaged text wins. Every other skill takes the owner's edited copy.
SKILLS_THIS_CHANGE_REWROTE: Final = frozenset(
    {
        "panels-worker-new-worker",
        "panels-worker-amend-worker",
    }
)
CHIEF_EMPLOYEE_ID: Final = "chief_of_staff"
CHIEF_LABEL: Final = "Chief of Staff"
DEFAULT_CHIEF_LAUNCH: Final = {
    "employee_backend": "codex",
    "employee_launch_model": "gpt-5.6-sol",
    "employee_launch_reasoning_effort": "medium",
}

SHIPPED_WORKER_TYPES: Final[tuple[dict[str, Any], ...]] = (
    {'dropped': {'gating_field': None,
                 'id': 'dropped',
                 'is_terminal': True,
                 'label': 'Dropped',
                 'ownership_mode': None},
     'fields': [{'id': 'kickoff', 'label': 'Kickoff'},
                {'id': 'success', 'label': 'Success'},
                {'id': 'approach', 'label': 'Approach'},
                {'id': 'plan', 'label': 'Plan'},
                {'id': 'implementation', 'label': 'Implementation'},
                {'id': 'closeout', 'label': 'Closeout'}],
     'label': 'Coding',
     'profile': {'default_backend': 'codex',
                 'default_model': 'gpt-5.6-sol',
                 'default_reasoning_effort': 'medium',
                 'specialist_skill': 'panels-worker-coding',
                 'toolset_profile': 'default'},
     'stages': [{'gating_field': 'kickoff',
                 'id': 'needs_kickoff',
                 'is_terminal': False,
                 'label': 'Kickoff',
                 'ownership_mode': 'worker'},
                {'gating_field': 'success',
                 'id': 'needs_success',
                 'is_terminal': False,
                 'label': 'Success',
                 'ownership_mode': 'worker'},
                {'gating_field': 'approach',
                 'id': 'needs_approach',
                 'is_terminal': False,
                 'label': 'Approach',
                 'ownership_mode': 'worker'},
                {'gating_field': 'plan',
                 'id': 'needs_plan',
                 'is_terminal': False,
                 'label': 'Plan',
                 'ownership_mode': 'worker'},
                {'gating_field': 'implementation',
                 'id': 'needs_implementation',
                 'is_terminal': False,
                 'label': 'Implementation',
                 'ownership_mode': 'worker'},
                {'gating_field': 'closeout',
                 'id': 'needs_closeout',
                 'is_terminal': False,
                 'label': 'Closeout',
                 'ownership_mode': 'worker'},
                {'gating_field': None,
                 'id': 'done',
                 'is_terminal': True,
                 'label': 'Done',
                 'ownership_mode': None}],
     'worker_type': 'coding'},
    {'dropped': {'gating_field': None,
                 'id': 'dropped',
                 'is_terminal': True,
                 'label': 'Dropped',
                 'ownership_mode': None},
     'fields': [{'id': 'kickoff', 'label': 'Kickoff'},
                {'id': 'execution', 'label': 'Execution'},
                {'id': 'closeout', 'label': 'Closeout'}],
     'label': 'General',
     'profile': {'default_backend': 'codex',
                 'default_model': 'gpt-5.6-sol',
                 'default_reasoning_effort': 'medium',
                 'specialist_skill': 'panels-worker-general',
                 'toolset_profile': 'default'},
     'stages': [{'gating_field': 'kickoff',
                 'id': 'needs_kickoff',
                 'is_terminal': False,
                 'label': 'Kickoff',
                 'ownership_mode': 'worker'},
                {'gating_field': 'execution',
                 'id': 'needs_execution',
                 'is_terminal': False,
                 'label': 'Execution',
                 'ownership_mode': 'worker'},
                {'gating_field': 'closeout',
                 'id': 'needs_closeout',
                 'is_terminal': False,
                 'label': 'Closeout',
                 'ownership_mode': 'worker'},
                {'gating_field': None,
                 'id': 'done',
                 'is_terminal': True,
                 'label': 'Done',
                 'ownership_mode': None}],
     'worker_type': 'general'},
    {'dropped': {'gating_field': None,
                 'id': 'dropped',
                 'is_terminal': True,
                 'label': 'Dropped',
                 'ownership_mode': None},
     'fields': [{'id': 'kickoff', 'label': 'Kickoff'},
                {'id': 'problem_understanding', 'label': 'Problem Understanding'},
                {'id': 'structural_diagnosis', 'label': 'Structural Diagnosis'},
                {'id': 'solution', 'label': 'Solution'},
                {'id': 'closeout', 'label': 'Closeout'}],
     'label': 'Debugging',
     'profile': {'default_backend': 'codex',
                 'default_model': 'gpt-5.6-sol',
                 'default_reasoning_effort': 'high',
                 'specialist_skill': 'panels-worker-debugging',
                 'toolset_profile': 'default'},
     'stages': [{'gating_field': 'kickoff',
                 'id': 'needs_kickoff',
                 'is_terminal': False,
                 'label': 'Kickoff',
                 'ownership_mode': 'worker'},
                {'gating_field': 'problem_understanding',
                 'id': 'needs_problem_understanding',
                 'is_terminal': False,
                 'label': 'Problem Understanding',
                 'ownership_mode': 'worker'},
                {'gating_field': 'structural_diagnosis',
                 'id': 'needs_structural_diagnosis',
                 'is_terminal': False,
                 'label': 'Structural Diagnosis',
                 'ownership_mode': 'worker'},
                {'gating_field': 'solution',
                 'id': 'needs_solution',
                 'is_terminal': False,
                 'label': 'Solution',
                 'ownership_mode': 'worker'},
                {'gating_field': 'closeout',
                 'id': 'needs_closeout',
                 'is_terminal': False,
                 'label': 'Closeout',
                 'ownership_mode': 'worker'},
                {'gating_field': None,
                 'id': 'done',
                 'is_terminal': True,
                 'label': 'Done',
                 'ownership_mode': None}],
     'worker_type': 'debugging'},
    {'dropped': {'gating_field': None,
                 'id': 'dropped',
                 'is_terminal': True,
                 'label': 'Dropped',
                 'ownership_mode': None},
     'fields': [{'id': 'kickoff', 'label': 'Kickoff'},
                {'id': 'understanding', 'label': 'Understanding'},
                {'id': 'stages', 'label': 'Stages'},
                {'id': 'thinking', 'label': 'Thinking'},
                {'id': 'runtime_defaults', 'label': 'Runtime Defaults'},
                {'id': 'drafting', 'label': 'Drafting'},
                {'id': 'closeout', 'label': 'Closeout'}],
     'label': 'New Worker',
     'profile': {'default_backend': 'codex',
                 'default_model': 'gpt-5.6-sol',
                 'default_reasoning_effort': 'medium',
                 'specialist_skill': 'panels-worker-new-worker',
                 'toolset_profile': 'default'},
     'stages': [{'gating_field': 'kickoff',
                 'id': 'needs_kickoff',
                 'is_terminal': False,
                 'label': 'Kickoff',
                 'ownership_mode': 'worker'},
                {'gating_field': 'understanding',
                 'id': 'needs_understanding',
                 'is_terminal': False,
                 'label': 'Understanding',
                 'ownership_mode': 'user'},
                {'gating_field': 'stages',
                 'id': 'needs_stages',
                 'is_terminal': False,
                 'label': 'Stages',
                 'ownership_mode': 'worker'},
                {'gating_field': 'thinking',
                 'id': 'needs_thinking',
                 'is_terminal': False,
                 'label': 'Thinking',
                 'ownership_mode': 'worker'},
                {'gating_field': 'runtime_defaults',
                 'id': 'needs_runtime_defaults',
                 'is_terminal': False,
                 'label': 'Runtime Defaults',
                 'ownership_mode': 'user'},
                {'gating_field': 'drafting',
                 'id': 'needs_drafting',
                 'is_terminal': False,
                 'label': 'Drafting',
                 'ownership_mode': 'worker'},
                {'gating_field': 'closeout',
                 'id': 'needs_closeout',
                 'is_terminal': False,
                 'label': 'Closeout',
                 'ownership_mode': 'worker'},
                {'gating_field': None,
                 'id': 'done',
                 'is_terminal': True,
                 'label': 'Done',
                 'ownership_mode': None}],
     'worker_type': 'new_worker'},
    {'dropped': {'gating_field': None,
                 'id': 'dropped',
                 'is_terminal': True,
                 'label': 'Dropped',
                 'ownership_mode': None},
     'fields': [{'id': 'kickoff', 'label': 'Kickoff'},
                {'id': 'amendment', 'label': 'Amendment'},
                {'id': 'drafting', 'label': 'Drafting'},
                {'id': 'closeout', 'label': 'Closeout'}],
     'label': 'Amend Worker',
     'profile': {'default_backend': 'codex',
                 'default_model': 'gpt-5.6-sol',
                 'default_reasoning_effort': 'medium',
                 'specialist_skill': 'panels-worker-amend-worker',
                 'toolset_profile': 'default'},
     'stages': [{'gating_field': 'kickoff',
                 'id': 'needs_kickoff',
                 'is_terminal': False,
                 'label': 'Kickoff',
                 'ownership_mode': 'worker'},
                {'gating_field': 'amendment',
                 'id': 'needs_amendment',
                 'is_terminal': False,
                 'label': 'Amendment',
                 'ownership_mode': 'user'},
                {'gating_field': 'drafting',
                 'id': 'needs_drafting',
                 'is_terminal': False,
                 'label': 'Drafting',
                 'ownership_mode': 'worker'},
                {'gating_field': 'closeout',
                 'id': 'needs_closeout',
                 'is_terminal': False,
                 'label': 'Closeout',
                 'ownership_mode': 'worker'},
                {'gating_field': None,
                 'id': 'done',
                 'is_terminal': True,
                 'label': 'Done',
                 'ownership_mode': None}],
     'worker_type': 'amend_worker'},
    {'dropped': {'gating_field': None,
                 'id': 'dropped',
                 'is_terminal': True,
                 'label': 'Dropped',
                 'ownership_mode': None},
     'fields': [{'id': 'kickoff', 'label': 'Kickoff'},
                {'id': 'understanding', 'label': 'Understanding'},
                {'id': 'research_plan', 'label': 'Research Plan'},
                {'id': 'research', 'label': 'Research'},
                {'id': 'answer', 'label': 'Answer'},
                {'id': 'follow_up', 'label': 'Follow-up'},
                {'id': 'closeout', 'label': 'Closeout'}],
     'label': 'Exploration',
     'profile': {'default_backend': 'codex',
                 'default_model': 'gpt-5.6-sol',
                 'default_reasoning_effort': 'medium',
                 'specialist_skill': 'panels-worker-exploration',
                 'toolset_profile': 'default'},
     'stages': [{'gating_field': 'kickoff',
                 'id': 'needs_kickoff',
                 'is_terminal': False,
                 'label': 'Kickoff',
                 'ownership_mode': 'worker'},
                {'gating_field': 'understanding',
                 'id': 'needs_understanding',
                 'is_terminal': False,
                 'label': 'Understanding',
                 'ownership_mode': 'user'},
                {'gating_field': 'research_plan',
                 'id': 'needs_research_plan',
                 'is_terminal': False,
                 'label': 'Research Plan',
                 'ownership_mode': 'worker'},
                {'gating_field': 'research',
                 'id': 'needs_research',
                 'is_terminal': False,
                 'label': 'Research',
                 'ownership_mode': 'worker'},
                {'gating_field': 'answer',
                 'id': 'needs_answer',
                 'is_terminal': False,
                 'label': 'Answer',
                 'ownership_mode': 'user'},
                {'gating_field': 'follow_up',
                 'id': 'needs_follow_up',
                 'is_terminal': False,
                 'label': 'Follow-up',
                 'ownership_mode': 'worker'},
                {'gating_field': 'closeout',
                 'id': 'needs_closeout',
                 'is_terminal': False,
                 'label': 'Closeout',
                 'ownership_mode': 'worker'},
                {'gating_field': None,
                 'id': 'done',
                 'is_terminal': True,
                 'label': 'Done',
                 'ownership_mode': None}],
     'worker_type': 'exploration'},
    {'dropped': {'gating_field': None,
                 'id': 'dropped',
                 'is_terminal': True,
                 'label': 'Dropped',
                 'ownership_mode': None},
     'fields': [{'id': 'kickoff', 'label': 'Kickoff'},
                {'id': 'rough_shape', 'label': 'Rough Shape'},
                {'id': 'question_tree', 'label': 'Question Tree'},
                {'id': 'question_answers', 'label': 'Question Answers'},
                {'id': 'ticket_outlines', 'label': 'Ticket Outlines'},
                {'id': 'closeout', 'label': 'Closeout'}],
     'label': 'Initiative Planning',
     'profile': {'default_backend': 'codex',
                 'default_model': 'gpt-5.6-sol',
                 'default_reasoning_effort': 'medium',
                 'specialist_skill': 'panels-worker-initiative-planning',
                 'toolset_profile': 'default'},
     'stages': [{'gating_field': 'kickoff',
                 'id': 'needs_kickoff',
                 'is_terminal': False,
                 'label': 'Kickoff',
                 'ownership_mode': 'worker'},
                {'gating_field': 'rough_shape',
                 'id': 'needs_rough_shape',
                 'is_terminal': False,
                 'label': 'Rough Shape',
                 'ownership_mode': 'worker'},
                {'gating_field': 'question_tree',
                 'id': 'needs_question_tree',
                 'is_terminal': False,
                 'label': 'Question Tree',
                 'ownership_mode': 'worker'},
                {'gating_field': 'question_answers',
                 'id': 'needs_question_answers',
                 'is_terminal': False,
                 'label': 'Question Answers',
                 'ownership_mode': 'user'},
                {'gating_field': 'ticket_outlines',
                 'id': 'needs_ticket_outlines',
                 'is_terminal': False,
                 'label': 'Ticket Outlines',
                 'ownership_mode': 'worker'},
                {'gating_field': 'closeout',
                 'id': 'needs_closeout',
                 'is_terminal': False,
                 'label': 'Closeout',
                 'ownership_mode': 'worker'},
                {'gating_field': None,
                 'id': 'done',
                 'is_terminal': True,
                 'label': 'Done',
                 'ownership_mode': None}],
     'worker_type': 'initiative_planning'},
    {'dropped': {'gating_field': None,
                 'id': 'dropped',
                 'is_terminal': True,
                 'label': 'Dropped',
                 'ownership_mode': None},
     'fields': [{'id': 'kickoff', 'label': 'Kickoff'},
                {'id': 'review', 'label': 'Review'},
                {'id': 'feedback', 'label': 'Feedback'},
                {'id': 'followups', 'label': 'Follow-ups'},
                {'id': 'closeout', 'label': 'Closeout'}],
     'label': 'Initiative Review',
     'profile': {'default_backend': 'codex',
                 'default_model': 'gpt-6-astra',
                 'default_reasoning_effort': 'high',
                 'specialist_skill': 'panels-worker-initiative-review',
                 'toolset_profile': 'default'},
     'stages': [{'gating_field': 'kickoff',
                 'id': 'needs_kickoff',
                 'is_terminal': False,
                 'label': 'Kickoff',
                 'ownership_mode': 'worker'},
                {'gating_field': 'review',
                 'id': 'needs_review',
                 'is_terminal': False,
                 'label': 'Review',
                 'ownership_mode': 'worker'},
                {'gating_field': 'feedback',
                 'id': 'needs_feedback',
                 'is_terminal': False,
                 'label': 'Feedback',
                 'ownership_mode': 'user'},
                {'gating_field': 'followups',
                 'id': 'needs_followups',
                 'is_terminal': False,
                 'label': 'Follow-ups',
                 'ownership_mode': 'worker'},
                {'gating_field': 'closeout',
                 'id': 'needs_closeout',
                 'is_terminal': False,
                 'label': 'Closeout',
                 'ownership_mode': 'worker'},
                {'gating_field': None,
                 'id': 'done',
                 'is_terminal': True,
                 'label': 'Done',
                 'ownership_mode': None}],
     'worker_type': 'initiative_review'},
    {'dropped': {'gating_field': None,
                 'id': 'dropped',
                 'is_terminal': True,
                 'label': 'Dropped',
                 'ownership_mode': None},
     'fields': [{'id': 'kickoff', 'label': 'Kickoff'},
                {'id': 'direction', 'label': 'Direction'},
                {'id': 'wireframe', 'label': 'Wireframe'},
                {'id': 'design', 'label': 'Design'},
                {'id': 'closeout', 'label': 'Closeout'}],
     'label': 'Product Design',
     'profile': {'default_backend': 'claude',
                 'default_model': 'opus[1m]',
                 'default_reasoning_effort': 'high',
                 'specialist_skill': 'panels-worker-product-design',
                 'toolset_profile': 'default'},
     'stages': [{'gating_field': 'kickoff',
                 'id': 'needs_kickoff',
                 'is_terminal': False,
                 'label': 'Kickoff',
                 'ownership_mode': 'worker'},
                {'gating_field': 'direction',
                 'id': 'needs_direction',
                 'is_terminal': False,
                 'label': 'Direction',
                 'ownership_mode': 'worker'},
                {'gating_field': 'wireframe',
                 'id': 'needs_wireframe',
                 'is_terminal': False,
                 'label': 'Wireframe',
                 'ownership_mode': 'user'},
                {'gating_field': 'design',
                 'id': 'needs_design',
                 'is_terminal': False,
                 'label': 'Design',
                 'ownership_mode': 'user'},
                {'gating_field': 'closeout',
                 'id': 'needs_closeout',
                 'is_terminal': False,
                 'label': 'Closeout',
                 'ownership_mode': 'worker'},
                {'gating_field': None,
                 'id': 'done',
                 'is_terminal': True,
                 'label': 'Done',
                 'ownership_mode': None}],
     'worker_type': 'product_design'},
    {'dropped': {'gating_field': None,
                 'id': 'dropped',
                 'is_terminal': True,
                 'label': 'Dropped',
                 'ownership_mode': None},
     'fields': [{'id': 'review', 'label': 'Previous Day Review'},
                {'id': 'direction', 'label': 'Direction'},
                {'id': 'day_changes', 'label': 'Day Changes'},
                {'id': 'closeout', 'label': 'Closeout'}],
     'label': 'Planning Day',
     'profile': {'default_backend': 'claude',
                 'default_model': 'opus[1m]',
                 'default_reasoning_effort': 'medium',
                 'specialist_skill': 'panels-worker-planning-day',
                 'toolset_profile': 'default'},
     'stages': [{'gating_field': 'review',
                 'id': 'needs_review',
                 'is_terminal': False,
                 'label': 'Previous Day Review',
                 'ownership_mode': 'worker'},
                {'gating_field': 'direction',
                 'id': 'needs_direction',
                 'is_terminal': False,
                 'label': 'Direction',
                 'ownership_mode': 'user'},
                {'gating_field': 'day_changes',
                 'id': 'needs_day_changes',
                 'is_terminal': False,
                 'label': 'Day Changes',
                 'ownership_mode': 'worker'},
                {'gating_field': 'closeout',
                 'id': 'needs_closeout',
                 'is_terminal': False,
                 'label': 'Closeout',
                 'ownership_mode': 'worker'},
                {'gating_field': None,
                 'id': 'done',
                 'is_terminal': True,
                 'label': 'Done',
                 'ownership_mode': None}],
     'worker_type': 'planning-day'},
    {'dropped': {'gating_field': None,
                 'id': 'dropped',
                 'is_terminal': True,
                 'label': 'Dropped',
                 'ownership_mode': None},
     'fields': [{'id': 'kickoff', 'label': 'Kickoff'},
                {'id': 'action', 'label': 'Action'},
                {'id': 'closeout', 'label': 'Closeout'}],
     'label': 'Planning Midday Check',
     'profile': {'default_backend': 'codex',
                 'default_model': 'gpt-5.6-terra',
                 'default_reasoning_effort': 'medium',
                 'specialist_skill': 'panels-worker-planning-midday-check',
                 'toolset_profile': 'default'},
     'stages': [{'gating_field': 'kickoff',
                 'id': 'needs_kickoff',
                 'is_terminal': False,
                 'label': 'Kickoff',
                 'ownership_mode': 'worker'},
                {'gating_field': 'action',
                 'id': 'needs_action',
                 'is_terminal': False,
                 'label': 'Action',
                 'ownership_mode': 'worker'},
                {'gating_field': 'closeout',
                 'id': 'needs_closeout',
                 'is_terminal': False,
                 'label': 'Closeout',
                 'ownership_mode': 'worker'},
                {'gating_field': None,
                 'id': 'done',
                 'is_terminal': True,
                 'label': 'Done',
                 'ownership_mode': None}],
     'worker_type': 'planning-midday-check'},
    {'dropped': {'gating_field': None,
                 'id': 'dropped',
                 'is_terminal': True,
                 'label': 'Dropped',
                 'ownership_mode': None},
     'fields': [{'id': 'kickoff', 'label': 'Kickoff'},
                {'id': 'review', 'label': 'Review'},
                {'id': 'next_sprint', 'label': 'Next Sprint'},
                {'id': 'closeout', 'label': 'Closeout'}],
     'label': 'Planning Sprint',
     'profile': {'default_backend': 'claude',
                 'default_model': 'opus[1m]',
                 'default_reasoning_effort': 'medium',
                 'specialist_skill': 'panels-worker-planning-sprint',
                 'toolset_profile': 'default'},
     'stages': [{'gating_field': 'kickoff',
                 'id': 'needs_kickoff',
                 'is_terminal': False,
                 'label': 'Kickoff',
                 'ownership_mode': 'worker'},
                {'gating_field': 'review',
                 'id': 'needs_review',
                 'is_terminal': False,
                 'label': 'Review',
                 'ownership_mode': 'worker'},
                {'gating_field': 'next_sprint',
                 'id': 'needs_next_sprint',
                 'is_terminal': False,
                 'label': 'Next Sprint',
                 'ownership_mode': 'worker'},
                {'gating_field': 'closeout',
                 'id': 'needs_closeout',
                 'is_terminal': False,
                 'label': 'Closeout',
                 'ownership_mode': 'worker'},
                {'gating_field': None,
                 'id': 'done',
                 'is_terminal': True,
                 'label': 'Done',
                 'ownership_mode': None}],
     'worker_type': 'planning-sprint'},
    {'dropped': {'gating_field': None,
                 'id': 'dropped',
                 'is_terminal': True,
                 'label': 'Dropped',
                 'ownership_mode': None},
     'fields': [{'id': 'kickoff', 'label': 'Kickoff'},
                {'id': 'outcome', 'label': 'Outcome'},
                {'id': 'closeout', 'label': 'Closeout'}],
     'label': 'Personal Task',
     'profile': {'default_backend': 'codex',
                 'default_model': 'gpt-5.6-luna',
                 'default_reasoning_effort': 'medium',
                 'specialist_skill': 'panels-worker-personal-task',
                 'toolset_profile': 'default'},
     'stages': [{'gating_field': 'kickoff',
                 'id': 'needs_kickoff',
                 'is_terminal': False,
                 'label': 'Kickoff',
                 'ownership_mode': 'user'},
                {'gating_field': 'outcome',
                 'id': 'needs_outcome',
                 'is_terminal': False,
                 'label': 'Outcome',
                 'ownership_mode': 'user'},
                {'gating_field': 'closeout',
                 'id': 'needs_closeout',
                 'is_terminal': False,
                 'label': 'Closeout',
                 'ownership_mode': 'worker'},
                {'gating_field': None,
                 'id': 'done',
                 'is_terminal': True,
                 'label': 'Done',
                 'ownership_mode': None}],
     'worker_type': 'personal'},
    {'dropped': {'gating_field': None,
                 'id': 'dropped',
                 'is_terminal': True,
                 'label': 'Dropped',
                 'ownership_mode': None},
     'fields': [{'id': 'kickoff', 'label': 'Kickoff'},
                {'id': 'research_plan', 'label': 'Research Plan'},
                {'id': 'research', 'label': 'Research'},
                {'id': 'closeout', 'label': 'Closeout'}],
     'label': 'Research',
     'profile': {'default_backend': 'claude',
                 'default_model': 'opus[1m]',
                 'default_reasoning_effort': 'high',
                 'specialist_skill': 'panels-worker-research',
                 'toolset_profile': 'default'},
     'stages': [{'gating_field': 'kickoff',
                 'id': 'needs_kickoff',
                 'is_terminal': False,
                 'label': 'Kickoff',
                 'ownership_mode': 'worker'},
                {'gating_field': 'research_plan',
                 'id': 'needs_research_plan',
                 'is_terminal': False,
                 'label': 'Research Plan',
                 'ownership_mode': 'worker'},
                {'gating_field': 'research',
                 'id': 'needs_research',
                 'is_terminal': False,
                 'label': 'Research',
                 'ownership_mode': 'worker'},
                {'gating_field': 'closeout',
                 'id': 'needs_closeout',
                 'is_terminal': False,
                 'label': 'Closeout',
                 'ownership_mode': 'worker'},
                {'gating_field': None,
                 'id': 'done',
                 'is_terminal': True,
                 'label': 'Done',
                 'ownership_mode': None}],
     'worker_type': 'research'},
)


def _database_parent() -> Path | None:
    database = op.get_bind().engine.url.database
    if not database:
        return None
    return Path(str(database)).expanduser().resolve().parent


def _packaged_skill_root() -> Path:
    return Path(__file__).resolve().parents[3] / "skills"


def _skill_sources(parent: Path | None) -> dict[str, str]:
    """Every managed skill's text: what the owner has been editing, then what shipped."""
    sources: dict[str, str] = {}
    packaged_root = _packaged_skill_root()
    roots = [] if parent is None else [parent / "skills"]
    roots.append(packaged_root)
    for root in roots:
        if not root.is_dir():
            continue
        for directory in sorted(root.iterdir(), key=lambda path: path.name):
            name = directory.name
            if name.startswith(".") or name in RETIRED_SKILL_NAMES or name in sources:
                continue
            if root != packaged_root and name in SKILLS_THIS_CHANGE_REWROTE:
                continue
            skill_file = directory / SKILL_FILE_NAME
            if directory.is_dir() and skill_file.is_file():
                sources[name] = skill_file.read_text(encoding="utf-8")
    return sources


def _stored_launch_defaults(parent: Path | None, key: str) -> dict[str, Any] | None:
    """The launch defaults the owner last saved for this Worker type or the Chief."""
    if parent is None:
        return None
    path = parent / "worker-settings" / key / "settings.json"
    if not path.is_file():
        return None
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except ValueError:
        return None
    stored = payload.get("launch_defaults") if isinstance(payload, dict) else None
    if not isinstance(stored, dict):
        return None
    backend = stored.get("employee_backend")
    model = stored.get("employee_launch_model")
    effort = stored.get("employee_launch_reasoning_effort")
    if not isinstance(backend, str) or not backend:
        return None
    # A block that named no model was repaired on read against the shipped one. There is
    # nothing left to repair against here, so such a block is left behind entirely.
    if not isinstance(model, str) or not model:
        return None
    if effort is not None and (not isinstance(effort, str) or not effort):
        return None
    return {
        "employee_backend": backend,
        "employee_launch_model": model,
        "employee_launch_reasoning_effort": effort,
    }


def upgrade() -> None:
    bind = op.get_bind()
    bind.exec_driver_sql(
        "CREATE TABLE managed_skills ("
        "skill_name TEXT PRIMARY KEY, "
        "source_text TEXT NOT NULL, "
        "updated_at INTEGER NOT NULL)"
    )
    bind.exec_driver_sql(
        "CREATE TABLE worker_types ("
        "worker_type TEXT PRIMARY KEY, "
        "position INTEGER NOT NULL, "
        "definition_json TEXT NOT NULL, "
        "updated_at INTEGER NOT NULL)"
    )
    bind.exec_driver_sql(
        "CREATE TABLE chief_settings ("
        "employee_id TEXT PRIMARY KEY, "
        "label TEXT NOT NULL, "
        "employee_backend TEXT NOT NULL, "
        "employee_launch_model TEXT NOT NULL, "
        "employee_launch_reasoning_effort TEXT)"
    )

    parent = _database_parent()
    now = 0
    for skill_name, source_text in _skill_sources(parent).items():
        bind.exec_driver_sql(
            "INSERT INTO managed_skills (skill_name, source_text, updated_at) VALUES (?, ?, ?)",
            (skill_name, source_text, now),
        )
    for position, shipped in enumerate(SHIPPED_WORKER_TYPES):
        definition = json.loads(json.dumps(shipped))
        launch_defaults = _stored_launch_defaults(parent, definition["worker_type"])
        if launch_defaults is not None:
            definition["profile"]["default_backend"] = launch_defaults["employee_backend"]
            definition["profile"]["default_model"] = launch_defaults["employee_launch_model"]
            definition["profile"]["default_reasoning_effort"] = launch_defaults[
                "employee_launch_reasoning_effort"
            ]
        bind.exec_driver_sql(
            "INSERT INTO worker_types (worker_type, position, definition_json, updated_at) "
            "VALUES (?, ?, ?, ?)",
            (
                definition["worker_type"],
                position,
                json.dumps(definition, ensure_ascii=False),
                now,
            ),
        )
    chief = _stored_launch_defaults(parent, CHIEF_EMPLOYEE_ID) or DEFAULT_CHIEF_LAUNCH
    bind.exec_driver_sql(
        "INSERT INTO chief_settings (employee_id, label, employee_backend, "
        "employee_launch_model, employee_launch_reasoning_effort) VALUES (?, ?, ?, ?, ?)",
        (
            CHIEF_EMPLOYEE_ID,
            CHIEF_LABEL,
            chief["employee_backend"],
            chief["employee_launch_model"],
            chief["employee_launch_reasoning_effort"],
        ),
    )


def downgrade() -> None:
    raise NotImplementedError("Panels migrations are forward-only")
